---
name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install ansible
          ansible --version
          printf '[defaults]\nroles_path=../' >ansible.cfg

      - name: Run Ansible syntax check
        run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check
